// <auto-generated />
using System;
using System.Collections.Generic;
using ExecuteUpdateDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ExecuteUpdateDemo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExecuteUpdateDemo.Data.Contestation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CreditId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("CreditReference")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<long?>("DeclarationId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("DeclarationReference")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("CreditId", "CreditReference")
                        .IsUnique()
                        .HasFilter("\"CreditId\" IS NOT NULL");

                    b.HasIndex("DeclarationId", "DeclarationReference")
                        .IsUnique()
                        .HasFilter("\"DeclarationId\" IS NOT NULL");

                    b.ToTable("Contestations");
                });

            modelBuilder.Entity("ExecuteUpdateDemo.Data.Credit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("DeclarationId")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("DeclarationReference")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.ComplexProperty<Dictionary<string, object>>("OptionalPeriod", "ExecuteUpdateDemo.Data.Credit.OptionalPeriod#OptionalPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime?>("DatumTm")
                                .HasColumnType("TIMESTAMP(7)")
                                .HasColumnName("uitkeringtm");

                            b1.Property<DateTime?>("DatumVanaf")
                                .HasColumnType("TIMESTAMP(7)")
                                .HasColumnName("uitkeringvanaf");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Period", "ExecuteUpdateDemo.Data.Credit.Period#Period", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("TIMESTAMP(7)");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("TIMESTAMP(7)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("DeclarationId", "DeclarationReference")
                        .IsUnique()
                        .HasFilter("\"DeclarationId\" IS NOT NULL");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("ExecuteUpdateDemo.Data.Declaration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("ExecuteUpdateDemo.Data.Contestation", b =>
                {
                    b.HasOne("ExecuteUpdateDemo.Data.Credit", "Credit")
                        .WithMany()
                        .HasForeignKey("CreditId");

                    b.HasOne("ExecuteUpdateDemo.Data.Declaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId");

                    b.Navigation("Credit");

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("ExecuteUpdateDemo.Data.Credit", b =>
                {
                    b.HasOne("ExecuteUpdateDemo.Data.Declaration", "Declaration")
                        .WithMany()
                        .HasForeignKey("DeclarationId");

                    b.Navigation("Declaration");
                });
#pragma warning restore 612, 618
        }
    }
}
